Heat Equation Simulator: sdl::SDLHeatmap Class Reference
sdl::SDLHeatmap Class Reference
Fullscreen temperature visualization.
#include <sdl_heatmap.hpp>
Public Member Functions
SDLHeatmap (SDLWindow &win, double t_min, double t_max)
void set_range (double t_min, double t_max)
void auto_range (const std::vector< double > &temps)
void auto_range_2d (const std::vector< std::vector< double > > &temps)
void draw_1d_fullscreen (const std::vector< double > &temps, const SimInfo &info)
void draw_2d_fullscreen (const std::vector< std::vector< double > > &temps, const SimInfo &info)
void draw_1d_cell (const std::vector< double > &temps, const SimInfo &info, int cell_x, int cell_y, int cell_w, int cell_h)
void draw_2d_cell (const std::vector< std::vector< double > > &temps, const SimInfo &info, int cell_x, int cell_y, int cell_w, int cell_h)
double get_min () const
double get_max () const
Private Member Functions
void temp_to_rgb (double t, Uint8 &r, Uint8 &g, Uint8 &b) const
void draw_number (SDL_Renderer *rend, int x, int y, double value) const
void draw_text (SDL_Renderer *rend, int x, int y, const char *text) const
void draw_colorbar (SDL_Renderer *rend, int x, int y, int w, int h) const
void draw_info_panel (SDL_Renderer *rend, const SimInfo &info) const
void draw_grid (SDL_Renderer *rend, int x0, int y0, int w, int h, int nx, int ny) const
Private Attributes
SDLWindow & win_
double t_min_
double t_max_
Detailed Description
Fullscreen temperature visualization.
Uses Inferno colormap (perceptually uniform). 2D uses bilinear interpolation for smooth gradients.
Definition at line 36 of file sdl_heatmap.hpp.
Constructor & Destructor Documentation
SDLHeatmap()
sdl::SDLHeatmap::SDLHeatmap (SDLWindow & win, double t_min, double t_max)
Definition at line 159 of file sdl_heatmap.cpp.
References t_max_, t_min_, and win_.
Member Function Documentation
auto_range()
void sdl::SDLHeatmap::auto_range (const std::vector< double > & temps)
Definition at line 167 of file sdl_heatmap.cpp.
References t_max_, and t_min_.
auto_range_2d()
void sdl::SDLHeatmap::auto_range_2d (const std::vector< std::vector< double > > & temps)
Definition at line 179 of file sdl_heatmap.cpp.
References t_max_, and t_min_.
draw_1d_cell()
void sdl::SDLHeatmap::draw_1d_cell (const std::vector< double > & temps, const SimInfo & info, int cell_x, int cell_y, int cell_w, int cell_h)
Definition at line 808 of file sdl_heatmap.cpp.
References sdl::SimInfo::alpha, draw_number(), draw_text(), sdl::SimInfo::L, sdl::SimInfo::material_name, sdl::SimInfo::paused, sdl::SimInfo::speed, t_max_, t_min_, temp_to_rgb(), sdl::SimInfo::time, sdl::SimInfo::tmax, and win_.
draw_1d_fullscreen()
void sdl::SDLHeatmap::draw_1d_fullscreen (const std::vector< double > & temps, const SimInfo & info)
Definition at line 418 of file sdl_heatmap.cpp.
References draw_colorbar(), draw_grid(), draw_info_panel(), draw_number(), draw_text(), sdl::SimInfo::L, t_max_, t_min_, temp_to_rgb(), sdl::SimInfo::u0, and win_.
draw_2d_cell()
void sdl::SDLHeatmap::draw_2d_cell (const std::vector< std::vector< double > > & temps, const SimInfo & info, int cell_x, int cell_y, int cell_w, int cell_h)
Definition at line 1076 of file sdl_heatmap.cpp.
References sdl::SimInfo::alpha, draw_number(), draw_text(), sdl::SimInfo::L, sdl::SimInfo::material_name, sdl::SimInfo::paused, sdl::SimInfo::speed, t_max_, t_min_, temp_to_rgb(), sdl::SimInfo::time, sdl::SimInfo::tmax, and win_.
draw_2d_fullscreen()
void sdl::SDLHeatmap::draw_2d_fullscreen (const std::vector< std::vector< double > > & temps, const SimInfo & info)
Definition at line 601 of file sdl_heatmap.cpp.
References draw_colorbar(), draw_grid(), draw_info_panel(), draw_number(), draw_text(), sdl::SimInfo::L, temp_to_rgb(), sdl::SimInfo::u0, and win_.
draw_colorbar()
void sdl::SDLHeatmap::draw_colorbar (SDL_Renderer * rend, int x, int y, int w, int h) const private
Definition at line 320 of file sdl_heatmap.cpp.
References draw_number(), draw_text(), t_max_, t_min_, and temp_to_rgb().
Referenced by draw_1d_fullscreen(), and draw_2d_fullscreen().
draw_grid()
void sdl::SDLHeatmap::draw_grid (SDL_Renderer * rend, int x0, int y0, int w, int h, int nx, int ny) const private
Definition at line 398 of file sdl_heatmap.cpp.
Referenced by draw_1d_fullscreen(), and draw_2d_fullscreen().
draw_info_panel()
void sdl::SDLHeatmap::draw_info_panel (SDL_Renderer * rend, const SimInfo & info) const private
Definition at line 350 of file sdl_heatmap.cpp.
References sdl::SimInfo::alpha, draw_text(), sdl::SimInfo::material_name, sdl::SimInfo::paused, sdl::SimInfo::speed, sdl::SimInfo::time, and sdl::SimInfo::tmax.
Referenced by draw_1d_fullscreen(), and draw_2d_fullscreen().
draw_number()
void sdl::SDLHeatmap::draw_number (SDL_Renderer * rend, int x, int y, double value) const private
Definition at line 250 of file sdl_heatmap.cpp.
References sdl::draw_digit().
Referenced by draw_1d_cell(), draw_1d_fullscreen(), draw_2d_cell(), draw_2d_fullscreen(), and draw_colorbar().
draw_text()
void sdl::SDLHeatmap::draw_text (SDL_Renderer * rend, int x, int y, const char * text) const private
Definition at line 273 of file sdl_heatmap.cpp.
References sdl::draw_digit(), and sdl::draw_letter().
Referenced by draw_1d_cell(), draw_1d_fullscreen(), draw_2d_cell(), draw_2d_fullscreen(), draw_colorbar(), and draw_info_panel().
get_max()
double sdl::SDLHeatmap::get_max () const inline
Definition at line 66 of file sdl_heatmap.hpp.
References t_max_.
get_min()
double sdl::SDLHeatmap::get_min () const inline
Definition at line 65 of file sdl_heatmap.hpp.
References t_min_.
set_range()
void sdl::SDLHeatmap::set_range (double t_min, double t_max)
Definition at line 162 of file sdl_heatmap.cpp.
References t_max_, and t_min_.
temp_to_rgb()
void sdl::SDLHeatmap::temp_to_rgb (double t, Uint8 & r, Uint8 & g, Uint8 & b) const private
Definition at line 235 of file sdl_heatmap.cpp.
References sdl::INFERNO_MAP, sdl::INFERNO_SIZE, t_max_, and t_min_.
Referenced by draw_1d_cell(), draw_1d_fullscreen(), draw_2d_cell(), draw_2d_fullscreen(), and draw_colorbar().
Member Data Documentation
t_max_
double sdl::SDLHeatmap::t_max_ private
Definition at line 40 of file sdl_heatmap.hpp.
Referenced by auto_range(), auto_range_2d(), draw_1d_cell(), draw_1d_fullscreen(), draw_2d_cell(), draw_colorbar(), get_max(), SDLHeatmap(), set_range(), and temp_to_rgb().
t_min_
double sdl::SDLHeatmap::t_min_ private
Definition at line 39 of file sdl_heatmap.hpp.
Referenced by auto_range(), auto_range_2d(), draw_1d_cell(), draw_1d_fullscreen(), draw_2d_cell(), draw_colorbar(), get_min(), SDLHeatmap(), set_range(), and temp_to_rgb().
win_
SDLWindow& sdl::SDLHeatmap::win_ private
Definition at line 38 of file sdl_heatmap.hpp.
Referenced by draw_1d_cell(), draw_1d_fullscreen(), draw_2d_cell(), draw_2d_fullscreen(), and SDLHeatmap().
The documentation for this class was generated from the following files:
sdl_heatmap.hpp
sdl_heatmap.cpp