Heat Equation Simulator: main.cpp File Reference
main.cpp File Reference
Console menu and SDL2 visualization launcher.
#include "sdl_core.hpp"
#include "sdl_app.hpp"
#include "material.hpp"
#include <iostream>
#include <string>
#include <limits>
#include <iomanip>
Functions
void clear_input ()
void print_header ()
int select_simulation_type ()
int select_material ()
bool get_parameters (double &L, double &tmax, double &u0, double &f)
bool confirm_and_start (int sim_type, int material_idx, double L, double tmax, double u0, double f)
int main ()
Detailed Description
Console menu and SDL2 visualization launcher.
Definition in file main.cpp.
Function Documentation
clear_input()
void clear_input ()
Definition at line 15 of file main.cpp.
Referenced by get_parameters(), select_material(), and select_simulation_type().
confirm_and_start()
bool confirm_and_start (int sim_type, int material_idx, double L, double tmax, double u0, double f)
Definition at line 102 of file main.cpp.
Referenced by main().
get_parameters()
bool get_parameters (double & L, double & tmax, double & u0, double & f)
Definition at line 64 of file main.cpp.
References clear_input().
Referenced by main().
main()
int main ()
Definition at line 120 of file main.cpp.
References sdl::SDLApp::BAR_1D, confirm_and_start(), ensiie::Materials::COPPER, get_parameters(), ensiie::Materials::GLASS, sdl::SDLCore::init(), ensiie::Materials::IRON, sdl::SDLApp::PLATE_2D, ensiie::Materials::POLYSTYRENE, print_header(), sdl::SDLCore::quit(), sdl::SDLApp::run(), select_material(), and select_simulation_type().
print_header()
void print_header ()
Definition at line 20 of file main.cpp.
Referenced by main().
select_material()
int select_material ()
Definition at line 44 of file main.cpp.
References clear_input().
Referenced by main().
select_simulation_type()
int select_simulation_type ()
Definition at line 28 of file main.cpp.
References clear_input().
Referenced by main().