Heat Equation Simulator: sdl Namespace Reference
sdl Namespace Reference
Classes
class SDLApp
Heat simulation with fullscreen visualization.
class SDLException
class SDLCore
struct SimInfo
Runtime simulation metadata for display.
class SDLHeatmap
Fullscreen temperature visualization.
class SDLWindow
Functions
static void draw_digit (SDL_Renderer *rend, int x, int y, int digit)
static void draw_letter (SDL_Renderer *rend, int x, int y, char c)
Variables
static const int INFERNO_SIZE = 256
static const unsigned char INFERNO_MAP [256][3]
Function Documentation
draw_digit()
void sdl::draw_digit (SDL_Renderer * rend, int x, int y, int digit) static
Definition at line 13 of file sdl_heatmap.cpp.
Referenced by sdl::SDLHeatmap::draw_number(), and sdl::SDLHeatmap::draw_text().
draw_letter()
void sdl::draw_letter (SDL_Renderer * rend, int x, int y, char c) static
Definition at line 40 of file sdl_heatmap.cpp.
Referenced by sdl::SDLHeatmap::draw_text().
Variable Documentation
INFERNO_MAP
const unsigned char sdl::INFERNO_MAP[256][3] static
Definition at line 200 of file sdl_heatmap.cpp.
Referenced by sdl::SDLHeatmap::temp_to_rgb().
INFERNO_SIZE
const int sdl::INFERNO_SIZE = 256 static
Definition at line 199 of file sdl_heatmap.cpp.
Referenced by sdl::SDLHeatmap::temp_to_rgb().